---
base_url: https://preview.hypertemplates.net
title: HyperTemplates
description: The pure-HTML templating system for the modern web.
copyright: "2025"
author:
    username: "@hypertemplates.net"
    name: HyperTemplates
    href: /
    favicon: /img/favicon-512x512.png
metadata: []
links:
  - rel: apple-touch-icon
    href: /img/apple-touch-icon.png
    sizes: 180x180
  - rel: icon
    href: /img/apple-touch-icon.png
    sizes: 180x180
  - rel: icon
    href: /img/favicon-128x128.png
    sizes: 128x128
  - rel: icon
    href: /img/favicon-192x192.png
    sizes: 192x192
  - rel: icon
    href: /img/favicon-256x256.png
    sizes: 256x256
  - rel: icon
    href: /img/favicon-512x512.png
    sizes: 512x512
  - rel: me
    href: https://github.com/hypertemplates
  - rel: me
    href: https://mastodon.social/@herdworks
config:
    tidy_mode: true
    theme_dir: theme
    tag_layout: "tag"
provider:
    kind: s3
    endpoint: https://5a8b6c901ff20ee02892cf121b1ead54.r2.cloudflarestorage.com
    store: hypertemplates-web-preview
    secrets:
        - name: access_key_id
          provider: env
          key: AWS_ACCESS_KEY_ID
        - name: secret_access_key
          provider: env
          key: AWS_SECRET_ACCESS_KEY
