---
base_url: https://preview.hypertemplates.net
title: HyperTemplates
description: A pure-HTML templating system for the modern web.
author:
  username: "@hypertemplates.net"
  name: HyperTemplates
  href: /
  favicon: /img/favicon-512x512.png
  email: contact@hypertemplates.net
favicons:
  - href: /img/apple-touch-icon.png
    sizes: 180x180
    rel: apple-touch-icon
  - href: /img/favicon-128x128.png
    sizes: 128x128
  - href: /img/favicon-192x192.png
    sizes: 192x192
  - href: /img/favicon-256x256.png
    sizes: 256x256
  - href: /img/favicon-512x512.png
    sizes: 512x512
banner: /banner.jpg
theme: hyper
copyright: "2024"
feeds:
  - link: /
  - link: /blog/
    tags:
      - blog
config:
    tidy_mode: true
    provider:
        kind: s3
        uri: https://5a8b6c901ff20ee02892cf121b1ead54.r2.cloudflarestorage.com
        store: hypertemplates-web-preview
        secrets:
            - name: access_key_id
              provider: env
              key: AWS_ACCESS_KEY_ID
            - name: secret_access_key
              provider: env
              key: AWS_SECRET_ACCESS_KEY
